title: ComicBox
email: adam@bibby.io
description: >- 
  ComicBox is a simple comicbook server that you host yourself.
baseurl: "/"
url: "https://comicbox.ca"
github_username:  comicbox

collections:
  - faq

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - readme.md
